apply plugin: 'com.android.library'

// Allow for project-level definition of certain versions. If such does not exist, use defaults.
// -- compileSdk
def dabAudioDecoderPluginCompileSdkVersion
if (rootProject.hasProperty('compileSdkVersion') && rootProject.ext.compileSdkVersion) {
    dabAudioDecoderPluginCompileSdkVersion = rootProject.ext.compileSdkVersion
} else {
    dabAudioDecoderPluginCompileSdkVersion = 33
}
// -- minSdk
def dabAudioDecoderPluginMinSdkVersion
if (rootProject.hasProperty('minSdkVersion') && rootProject.ext.minSdkVersion) {
    dabAudioDecoderPluginMinSdkVersion = rootProject.ext.minSdkVersion
} else {
    dabAudioDecoderPluginMinSdkVersion = 23
}
// -- targetSdk
def dabAudioDecoderPluginTargetSdkVersion
if (rootProject.hasProperty('targetSdkVersion') && rootProject.ext.targetSdkVersion) {
    dabAudioDecoderPluginTargetSdkVersion = rootProject.ext.targetSdkVersion
} else {
    dabAudioDecoderPluginTargetSdkVersion = 31
}
println("dabAudioDecoderPluginplugin: targetSdk:" + dabAudioDecoderPluginTargetSdkVersion
        + ", compileSdk:" + dabAudioDecoderPluginCompileSdkVersion
        + ", minSdkVersion:" + dabAudioDecoderPluginMinSdkVersion)


android {
    compileSdkVersion dabAudioDecoderPluginCompileSdkVersion
    namespace 'de.irt.dabaudiodecoderplugininterface'
    defaultConfig {
        minSdkVersion dabAudioDecoderPluginMinSdkVersion
        //noinspection OldTargetApi
        targetSdkVersion dabAudioDecoderPluginTargetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    buildFeatures {
        aidl true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
